var zidtocountry = {
	"Europe/Andorra": ["Andorra"],
	"Asia/Dubai": ["United Arab Emirates"],
	"Asia/Kabul": ["Afghanistan"],
	"America/Antigua": ["Antigua and Barbuda"],
	"America/Anguilla": ["Anguilla"],
	"Europe/Tirane": ["Albania"],
	"Asia/Yerevan": ["Armenia"],
	"America/Curacao": ["St Maarten (Dutch part)"],
	"Africa/Luanda": ["Angola"],
	"Antarctica/South_Pole": ["Amundsen-Scott South Pole Station, Antarctica"],
	"Antarctica/Casey": ["Casey Station, Antarctica"],
	"Antarctica/Davis": ["Davis Station, Antarctica"],
	"Antarctica/DumontDUrville": ["Dumont d'Urville Station, Antarctica"],
	"Antarctica/Macquarie": ["Macquarie Island"],
	"Antarctica/Mawson": ["Mawson Station, Antarctica"],
	"Antarctica/McMurdo": ["McMurdo Station, Antarctica"],
	"Antarctica/Palmer": ["Palmer Station, Antarctica"],
	"Antarctica/Rothera": ["Rothera Research Station, Antarctica"],
	"Antarctica/Syowa": ["Showa Station, Antarctica"],
	"Antarctica/Vostok": ["Vostok Station, Antarctica"],
	"America/Argentina/Buenos_Aires": ["Argentina"],
	"America/Argentina/Catamarca": ["Argentina"],
	"America/Argentina/Tucuman": ["Argentina"],
	"America/Argentina/Rio_Gallegos": ["Argentina"],
	"America/Argentina/Cordoba": ["Argentina"],
	"America/Argentina/Jujuy": ["Argentina"],
	"America/Argentina/San_Luis": ["Argentina"],
	"America/Argentina/La_Rioja": ["Argentina"],
	"America/Argentina/Mendoza": ["Argentina"],
	"America/Argentina/Salta": ["Argentina"],
	"America/Argentina/San_Juan": ["Argentina"],
	"America/Argentina/Ushuaia": ["Argentina"],	
	"Pacific/Pago_Pago": ["Samoa"],
	"Europe/Vienna": ["Austria"],
	"Australia/Sydney": ["Australia"],
	"Australia/Darwin": ["Australia"],
	"Australia/Brisbane": ["Australia"],
	"Australia/Adelaide": ["Australia"],
	"Australia/Hobart": ["Australia"],
	"Australia/Melbourne": ["Australia"],
	"Australia/Perth": ["Australia"],
	"America/Aruba": ["Aruba"],
	"Europe/Mariehamn": ["Aaland Islands"],
	"Asia/Baku": ["Azerbaijan"],
	"Europe/Sarajevo": ["Bosnia and Herzegovina"],
	"America/Barbados": ["Barbados"],
	"Asia/Dhaka": ["Bangladesh"],
	"Europe/Brussels": ["Belgium"],
	"Africa/Ouagadougou": ["Burkina Faso"],
	"Europe/Sofia": ["Bulgaria"],
	"Asia/Bahrain": ["Bahrain"],
	"Africa/Bujumbura": ["Burundi"],
	"Africa/Porto-Novo": ["Benin"],
	"America/St_Barthelemy": ["St Barthelemy"],
	"Atlantic/Bermuda": ["Bermuda"],
	"Asia/Brunei": ["Brunei"],
	"America/La_Paz": ["Bolivia"],
	"America/Rio_Branco": ["Brazil"],
	"America/Maceio": ["Brazil"],
	"America/Sao_Paulo": ["Brazil"],
	"America/Manaus": ["Brazil"],
	"America/Bahia": ["Brazil"],
	"America/Fortaleza": ["Brazil"],
	"America/Campo_Grande": ["Brazil"],
	"America/Belem": ["Brazil"],
	"America/Cuiaba": ["Brazil"],
	"America/Recife": ["Brazil"],
	"America/Porto_Velho": ["Brazil"],
	"America/Boa_Vista": ["Brazil"],
	"America/Araguaina": ["Brazil"],
	"America/Nassau": ["Bahamas"],
	"Asia/Thimphu": ["Bhutan"],
	"Africa/Gaborone": ["Botswana"],
	"Europe/Minsk": ["Belarus"],
	"America/Belize": ["Belize"],
	"America/Edmonton": ["Canada"],
	"America/Vancouver": ["Canada"],
	"America/Winnipeg": ["Canada"],
	"America/Halifax": ["Canada"],
	"America/St_Johns": ["Canada"],
	"America/Yellowknife": ["Canada"],
	"America/Rankin_Inlet": ["Canada"],
	"America/Toronto": ["Canada"],
	"America/Montreal": ["Canada"],
	"America/Regina": ["Canada"],
	"America/Whitehorse": ["Canada"],
	"Indian/Cocos": ["Cocos (Keeling) Islands"],
	"Africa/Kinshasa": ["Democratic Republic of the Congo"],
	"Africa/Lubumbashi": ["Democratic Republic of the Congo"],
	"Africa/Bangui": ["Central African Republic"],
	"Africa/Brazzaville": ["Republic of the Congo"],
	"Europe/Zurich": ["Switzerland"],
	"Africa/Abidjan": ["Cote d'Ivoire"],
	"Pacific/Rarotonga": ["Cook Islands"],
	"America/Santiago": ["Chile"],
	"Africa/Lagos": ["Nigeria"],
	"Asia/Shanghai": ["China"],
	"Asia/Harbin": ["China"],
	"Asia/Chongqing": ["China"],
	"Asia/Urumqi": ["China"],
	"America/Bogota": ["Colombia"],
	"America/Costa_Rica": ["Costa Rica"],
	"America/Havana": ["Cuba"],
	"Atlantic/Cape_Verde": ["Cape Verde"],
	"Indian/Christmas": ["Christmas Island"],
	"Asia/Nicosia": ["Cyprus"],
	"Europe/Prague": ["Czech Republic"],
	"Europe/Berlin": ["Germany"],
	"Africa/Djibouti": ["Djibouti"],
	"Europe/Copenhagen": ["Denmark"],
	"America/Dominica": ["Dominica"],
	"America/Santo_Domingo": ["Dominican Republic"],
	"Africa/Algiers": ["Algeria"],
	"Pacific/Galapagos": ["Ecuador"],
	"America/Guayaquil": ["Ecuador"],
	"Europe/Tallinn": ["Estonia"],
	"Africa/Cairo": ["Egypt"],
	"Africa/El_Aaiun": ["Western Sahara"],
	"Africa/Asmara": ["Eritrea"],
	"Europe/Madrid": ["Spain"],
	"Africa/Ceuta": ["Spain"],
	"Atlantic/Canary": ["Spain"],
	"Africa/Addis_Ababa": ["Ethiopia"],
	"Europe/Helsinki": ["Finland"],
	"Pacific/Fiji": ["Fiji"],
	"Atlantic/Stanley": ["Falkland Islands"],
	"Pacific/Pohnpei": ["Federated States of Micronesia"],
	"Atlantic/Faroe": ["Faroe Islands"],
	"Africa/Libreville": ["Gabon"],
	"Europe/London": ["Great Britain and Northern Ireland"],
	"America/Grenada": ["Grenada"],
	"Asia/Tbilisi": ["Georgia"],
	"America/Cayenne": ["French Guiana"],
	"Europe/Guernsey": ["Guernsey"],
	"Africa/Accra": ["Ghana"],
	"Europe/Gibraltar": ["Gibraltar"],
	"America/Thule": ["Greenland"],
	"America/Godthab": ["Greenland"],
	"Africa/Banjul": ["Gambia"],
	"Africa/Conakry": ["Guinea"],
	"America/Guadeloupe": ["Guadeloupe"],
	"Africa/Malabo": ["Equatorial Guinea"],
	"Europe/Athens": ["Greece"],
	"Atlantic/South_Georgia": ["South Georgia and the South Sandwich Islands"],
	"America/Guatemala": ["Guatemala"],
	"Pacific/Guam": ["Guam"],
	"Africa/Bissau": ["Guinea-Bissau"],
	"America/Guyana": ["Guyana"],
	"Asia/Hong_Kong": ["Hong Kong"],
	"America/Tegucigalpa": ["Honduras"],
	"Europe/Zagreb": ["Croatia"],
	"America/Port-au-Prince": ["Haiti"],
	"Europe/Budapest": ["Hungary"],
	"Asia/Pontianak": ["Indonesia"],
	"Asia/Makassar": ["Indonesia"],
	"Asia/Jakarta": ["Indonesia"],
	"Asia/Jayapura": ["Indonesia"],
	"Europe/Dublin": ["Ireland"],
	"Asia/Jerusalem": ["Israel"],
	"Europe/Isle_of_Man": ["Isle of Man"],
	"Asia/Kolkata": ["India"],
	"Indian/Chagos": ["British Indian Ocean Territory"],
	"Asia/Baghdad": ["Iraq"],
	"Asia/Tehran": ["Iran"],
	"Atlantic/Reykjavik": ["Iceland"],
	"Europe/Rome": ["Italy"],
	"Europe/Jersey": ["Jersey"],
	"America/Jamaica": ["Jamaica"],
	"Asia/Amman": ["Jordan"],
	"Asia/Tokyo": ["Japan"],
	"Africa/Nairobi": ["Kenya"],
	"Asia/Bishkek": ["Kyrgyzstan"],
	"Asia/Phnom_Penh": ["Cambodia"],
	"Pacific/Tarawa": ["Kiribati"],
	"Indian/Comoro": ["Comoros"],
	"America/St_Kitts": ["St Kitts and Nevis"],
	"Asia/Pyongyang": ["North Korea"],
	"Asia/Seoul": ["South Korea"],
	"Asia/Kuwait": ["Kuwait"],
	"America/Cayman": ["Cayman Islands"],
	"Asia/Almaty": ["Kazakhstan"],
	"Asia/Qyzylorda": ["Kazakhstan"],
	"Asia/Aqtobe": ["Kazakhstan"],
	"Asia/Aqtau": ["Kazakhstan"],
	"Asia/Oral": ["Kazakhstan"],
	"Asia/Vientiane": ["Laos"],
	"Asia/Beirut": ["Lebanon"],
	"America/St_Lucia": ["St Lucia"],
	"Europe/Vaduz": ["Liechtenstein"],
	"Asia/Colombo": ["Sri Lanka"],
	"Africa/Monrovia": ["Liberia"],
	"Africa/Maseru": ["Lesotho"],
	"Europe/Vilnius": ["Lithuania"],
	"Europe/Luxembourg": ["Luxembourg"],
	"Europe/Riga": ["Latvia"],
	"Africa/Tripoli": ["Libya"],
	"Africa/Casablanca": ["Morocco"],
	"Europe/Monaco": ["Monaco"],
	"Europe/Chisinau": ["Moldova"],
	"Europe/Podgorica": ["Montenegro"],
	"America/Marigot": ["St Martin (French part)"],
	"Indian/Antananarivo": ["Madagascar"],
	"Pacific/Kwajalein": ["Marshall Islands"],
	"Europe/Skopje": ["Macedonia"],
	"Africa/Bamako": ["Mali"],
	"Asia/Rangoon": ["Myanmar (Burma)"],
	"Asia/Choibalsan": ["Mongolia"],
	"Asia/Ulaanbaatar": ["Mongolia"],
	"Asia/Hovd": ["Mongolia"],
	"Asia/Macau": ["Macau"],
	"Pacific/Saipan": ["Northern Mariana Islands"],
	"America/Martinique": ["Martinique"],
	"Africa/Nouakchott": ["Mauritania"],
	"America/Montserrat": ["Montserrat"],
	"Europe/Malta": ["Malta"],
	"Indian/Mauritius": ["Mauritius"],
	"Indian/Maldives": ["Maldives"],
	"Africa/Blantyre": ["Malawi"],
	"America/Mexico_City": ["Mexico"],
	"America/Tijuana": ["Mexico"],
	"America/Hermosillo": ["Mexico"],
	"America/Merida": ["Mexico"],
	"America/Chihuahua": ["Mexico"],
	"America/Monterrey": ["Mexico"],
	"America/Mazatlan": ["Mexico"],
	"America/Cancun": ["Mexico"],
	"Asia/Kuala_Lumpur": ["Malaysia"],
	"Asia/Kuching": ["Malaysia"],
	"Africa/Maputo": ["Mozambique"],
	"Africa/Windhoek": ["Namibia"],
	"Pacific/Noumea": ["New Caledonia"],
	"Africa/Niamey": ["Niger"],
	"Pacific/Norfolk": ["Norfolk Island"],
	"America/Managua": ["Nicaragua"],
	"Europe/Amsterdam": ["Netherlands"],
	"Europe/Oslo": ["Norway"],
	"Asia/Kathmandu": ["Nepal"],
	"Pacific/Nauru": ["Nauru"],
	"Pacific/Niue": ["Niue"],
	"Pacific/Auckland": ["New Zealand"],
	"Pacific/Chatham": ["Chatham Islands, New Zealand"],
	"Pacific/Rarotonga": ["Cook Islands, New Zealand"],
	"Asia/Muscat": ["Oman"],
	"America/Panama": ["Panama"],
	"America/Lima": ["Peru"],
	"Pacific/Marquesas": ["French Polynesia"],
	"Pacific/Port_Moresby": ["Papua New Guinea"],
	"Asia/Manila": ["Philippines"],
	"Asia/Karachi": ["Pakistan"],
	"Europe/Warsaw": ["Poland"],
	"America/Miquelon": ["St Pierre and Miquelon"],
	"Pacific/Pitcairn": ["Pitcairn"],
	"America/Puerto_Rico": ["Puerto Rico"],
	"Asia/Gaza": ["Palestine"],
	"Europe/Lisbon": ["Portugal"],
	"Atlantic/Madeira": ["Portugal"],
	"Atlantic/Azores": ["Portugal"],
	"Pacific/Palau": ["Palau"],
	"America/Asuncion": ["Paraguay"],
	"Asia/Qatar": ["Qatar"],
	"Indian/Reunion": ["Reunion"],
	"Europe/Bucharest": ["Romania"],
	"Europe/Volgograd": ["Russia"],
	"Asia/Irkutsk": ["Russia"],
	"Asia/Novokuznetsk": ["Russia"],
	"Asia/Novosibirsk": ["Russia"],
	"Asia/Vladivostok": ["Russia"],
	"Europe/Moscow": ["Russia"],
	"Europe/Samara": ["Russia"],
	"Asia/Yekaterinburg": ["Russia"],
	"Asia/Anadyr": ["Russia"],
	"Asia/Krasnoyarsk": ["Russia"],
	"Europe/Kaliningrad": ["Russia"],
	"Asia/Kamchatka": ["Russia"],
	"Asia/Omsk": ["Russia"],
	"Asia/Magadan": ["Russia"],
	"Asia/Yakutsk": ["Russia"],
	"Asia/Sakhalin": ["Russia"],
	"Africa/Kigali": ["Rwanda"],
	"Asia/Riyadh": ["Saudi Arabia"],
	"Pacific/Guadalcanal": ["Solomon Islands"],
	"Indian/Mahe": ["Seychelles"],
	"Africa/Khartoum": ["Sudan"],
	"Europe/Stockholm": ["Sweden"],
	"Asia/Singapore": ["Singapore"],
	"Atlantic/St_Helena": ["St Helena"],
	"Europe/Ljubljana": ["Slovenia"],
	"Arctic/Longyearbyen": ["Svalbard and Jan Mayen"],
	"Europe/Bratislava": ["Slovakia"],
	"Africa/Freetown": ["Sierra Leone"],
	"Europe/San_Marino": ["San Marino"],
	"Africa/Dakar": ["Senegal"],
	"Africa/Mogadishu": ["Somalia"],
	"America/Paramaribo": ["Suriname"],
	"Africa/Juba": ["South Sudan"],
	"Africa/Sao_Tome": ["Sao Tome and Principe"],
	"America/El_Salvador": ["El Salvador"],
	"Asia/Damascus": ["Syria"],
	"Africa/Mbabane": ["Swaziland"],
	"America/Grand_Turk": ["Turks and Caicos Islands"],
	"Africa/Ndjamena": ["Chad"],
	"Indian/Kerguelen": ["French Southern and Antarctic Lands"],
	"Africa/Lome": ["Togo"],
	"Asia/Bangkok": ["Thailand"],
	"Asia/Dushanbe": ["Tajikistan"],
	"Pacific/Fakaofo": ["Tokelau"],
	"Asia/Dili": ["East Timor"],
	"Asia/Ashgabat": ["Turkmenistan"],
	"Africa/Tunis": ["Tunisia"],
	"Pacific/Tongatapu": ["Tonga"],
	"Asia/Istanbul": ["Turkey"],
	"America/Port_of_Spain": ["Trinidad and Tobago"],
	"Pacific/Funafuti": ["Tuvalu"],
	"Asia/Taipei": ["Taiwan"],
	"Africa/Dar_es_Salaam": ["Tanzania"],
	"Europe/Kiev": ["Ukraine"],
	"Europe/Uzhgorod": ["Ukraine"],
	"Europe/Zaporozhye": ["Ukraine"],
	"Europe/Simferopol": ["Ukraine"],
	"Africa/Kampala": ["Uganda"],
	"Pacific/Wake": ["US Minor Outlying Islands"],
	"America/Anchorage": ["United States"],
	"America/Chicago": ["United States"],
	"America/Phoenix": ["United States"],
	"America/Los_Angeles": ["United States"],
	"America/Denver": ["United States"],
	"America/New_York": ["United States"],
	"Pacific/Honolulu": ["Hawaii, USA"],
	"America/Indiana/Indianapolis": ["United States"],
	"America/Montevideo": ["Uruguay"],
	"Asia/Tashkent": ["Uzbekistan"],
	"Asia/Samarkand": ["Uzbekistan"],
	"Europe/Vatican": ["Vatican City"],
	"America/St_Vincent": ["St Vincent"],
	"America/Caracas": ["Venezuela"],
	"America/Tortola": ["Virgin Islands (UK)"],
	"America/St_Thomas": ["Virgin Islands (US)"],
	"Pacific/Efate": ["Vanuatu"],
	"Pacific/Wallis": ["Wallis and Futuna"],
	"Asia/Aden": ["Yemen"],
	"Indian/Mayotte": ["Mayotte"],
	"Africa/Johannesburg": ["South Africa"],
	"Africa/Lusaka": ["Zambia"],
	"Africa/Harare": ["Zimbabwe"],
	//for whatever reason some where missing, so:
	"Asia/Ho_Chi_Minh": ["Vietnam"],
	"Africa/Douala": ["Cameroon"],
	"America/Adak": ["Aleutian Islands, USA"],
	"America/Atikokan": ["Canada"],
	"America/Bahia_Banderas": ["Mexico"],
	"America/Blanc-Sablon": ["Quebec, Canada"],
	"America/Boise": ["United States"],
	"America/Cambridge_Bay": ["Canada"],
	"America/Creston": ["Canada"],
	"America/Danmarkshavn": ["Greenland"],
	"America/Dawson": ["Canada"],
	"America/Dawson_Creek": ["Canada"],
	"America/Detroit": ["United States"],
	"America/Eirunepe": ["Brazil"],
	"America/Glace_Bay": ["Canada"],
	"America/Goose_Bay": ["Canada"],
	"America/Indiana/Knox": ["United States"],
	"America/Indiana/Marengo": ["United States"],
	"America/Indiana/Petersburg": ["United States"],
	"America/Indiana/Tell_City": ["United States"],
	"America/Indiana/Vevay": ["United States"],
	"America/Indiana/Vincennes": ["United States"],
	"America/Indiana/Winamac": ["United States"],
	"America/Inuvik": ["Canada"],
	"America/Iqaluit": ["Canada"],
	"America/Juneau": ["Alaska, USA"],
	"America/Kentucky/Louisville": ["United States"],
	"America/Kentucky/Monticello": ["United States"],
	"America/Matamoros": ["Mexico"],
	"America/Menominee": ["United States"],
	"America/Metlakatla": ["United States"],
	"America/Moncton": ["Canada"],
	"America/Nipigon": ["Canada"],
	"America/Nome": ["Alaska, USA"],
	"America/Noronha": ["Brazil"],
	"America/North_Dakota/Beulah": ["United States"],
	"America/North_Dakota/Center": ["United States"],
	"America/North_Dakota/New_Salem": ["United States"],
	"America/Ojinaga": ["Mexico"],
	"America/Pangnirtung": ["Canada"],
	"America/Rainy_River": ["Canada"],
	"America/Resolute": ["Canada"],
	"America/Santa_Isabel": ["Mexico"],
	"America/Santarem": ["Brazil"],
	"America/Scoresbysund": ["Greenland"],
	"America/Sitka": ["Alaska, USA"],
	"America/Swift_Current": ["Canada"],
	"America/Thunder_Bay": ["Canada"],
	"America/Yakutat": ["Alaska, USA"],
	"Asia/Hebron": ["Palestine"],
	"Asia/Kashgar": ["China"],
	"Asia/Khandyga": ["Russia"],
	"Asia/Ust-Nera": ["Russia"],
	"Australia/Broken_Hill": ["Australia"],
	"Australia/Currie": ["Australia"],
	"Australia/Eucla": ["Australia"],
	"Australia/Lindeman": ["Australia"],
	"Australia/Lord_Howe": ["Australia"],
	"Europe/Belgrade": ["Serbia"],
	"Europe/Istanbul": ["Turkey"],
	"Europe/Paris": ["France"],
	"Pacific/Apia": ["Samoa"],
	"Pacific/Chuuk": ["Federated States of Micronesia"],
	"Pacific/Easter": ["Easter Island"],
	"Pacific/Enderbury": ["Kiribati"],
	"Pacific/Gambier": ["French Polynesia"],
	"Pacific/Johnston": ["United States Minor Outlying Islands"],
	"Pacific/Kiritimati": ["Kiribati"],
	"Pacific/Kosrae": ["Federated States of Micronesia"],
	"Pacific/Majuro": ["Marshall Islands"],
	"Pacific/Midway": ["Midway Atoll"],
	"Pacific/Tahiti": ["French Polynesia"]
};
moment.tz.add({
    "ztc": zidtocountry,
});
//takes a zid, returns the country.
function ztc(zid){
	if (zidtocountry.hasOwnProperty(zid)){
		return zidtocountry[zid][0];
	}else{
		return false;
	};
};
